# Generated by Django 2.1.7 on 2019-03-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
